apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-porkbun.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cert-manager-webhook-porkbun.name" . }}
    chart: {{ include "cert-manager-webhook-porkbun.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "cert-manager-webhook-porkbun.selectorLabels" . | nindent 4 }}
